#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 25 15:02:46 2022

@author: crystalhansen
"""

import random
n = random.random()
print(n*100)

n = random.randint(0,22)
print(n)


randomlist = []
for i in range(0,5):
 n = random.randint(1,30)
 randomlist.append(n)
 print(randomlist)


#Generate 5 random numbers between 10 and 30
randomlist2 = random.sample(range(10, 30), 5)
print(randomlist2)


#random.choice(list)



number_list = [111, 222, 333, 444, 555]
# random item from list
print(random.choice(number_list))
# Output 222